# frozen_string_literal: true
# Generated by 18xxtools — edit freely

module Engine
  module Game
    module GGGame
      module Entities
        # ── Private Companies ─────────────────────────────────────────────────
        COMPANIES = [
          {
            name: 'L-Train Concession',
            value: 100,
            revenue: 0,
            desc: 'Grants the owning corporation a permanent L train.',
            sym: '',
            abilities: [
              { type: 'generic' },
            ],
          },
        ].freeze

        # ── Corporations ──────────────────────────────────────────────────────
        # (nothing to configure)

        # ── Minors ────────────────────────────────────────────────────────────
        # (nothing to configure)

      end
    end
  end
end
