# frozen_string_literal: true
# Generated by 18xxtools — edit freely

require_relative '../base'
require_relative 'entities'
require_relative 'map'

module Engine
  module Game
    module GForge25
      class Game < Engine::Game::Base
        include Entities
        include Map

        # ── Trains ───────────────────────────────────────────────────────────
        TRAINS = [
          { name: 'L', distance: 1, price: 100, num: 1 }
        ].freeze

        # ── Phases ───────────────────────────────────────────────────────────
        # (nothing to configure)

        # ── Bank & Players ────────────────────────────────────────────────────
        PLAYERS_RANGE = [2, 6]
        BANK_CASH = 12_000
        STARTING_CASH = { 2 => 0, 3 => 0, 4 => 0, 5 => 0, 6 => 0 }.freeze
        CERT_LIMIT = { 2 => 0, 3 => 0, 4 => 0, 5 => 0, 6 => 0 }.freeze

        # ── Corporation Rules ─────────────────────────────────────────────────
        CAPITALIZATION = :full
        HOME_TOKEN_TIMING = :operate
        MARKET_SHARE_LIMIT = 50
        TRACK_RESTRICTION = :semi_restrictive
        BANKRUPTCY_ALLOWED = true
        BANKRUPTCY_ENDS_GAME_AFTER = :one

        # ── Stock Round ───────────────────────────────────────────────────────
        SELL_BUY_ORDER = :sell_buy_or_buy_sell
        SELL_MOVEMENT = :down_share
        POOL_SHARE_DROP = :none
        MUST_SELL_IN_BLOCKS = false
        SELL_AFTER = :first

        MARKET = [
                  [100,110,120,130,140,150,160,170,180,190,200]
                ].freeze

        # ── Operating Round ───────────────────────────────────────────────────
        MUST_BUY_TRAIN = :route
        ALLOW_REMOVING_TOWNS = false
        EBUY_FROM_OTHERS = :value
        EBUY_DEPOT_TRAIN_MUST_BE_CHEAPEST = true
        MUST_EMERGENCY_ISSUE_BEFORE_EBUY = false
        EBUY_OWNER_MUST_HELP = false
        EBUY_CAN_SELL_SHARES = true
        EBUY_PRES_SWAP = true
        EBUY_CAN_TAKE_PLAYER_LOAN = false

        TILE_LAYS = [{ lay: true, upgrade: true }, { lay: true, upgrade: false, cost: 20 }].freeze

        # ── Game Flow ─────────────────────────────────────────────────────────
        # Initial round: Waterfall auction — configure auction in Companies panel

        # ── Game End ──────────────────────────────────────────────────────────
        # GAME_END_CHECK not configured

        # ── Special Constants ─────────────────────────────────────────────────
        # (nothing to configure)

        # ── Round Methods ─────────────────────────────────────────────────────
        # (nothing to configure)

        # ── Methods ───────────────────────────────────────────────────────────
        # Private company accessors — reference by name in custom step code.

        def l_train_concession
          @l_train_concession ||= company_by_id('')
        end

      end
    end
  end
end
