# frozen_string_literal: true
# Generated by 18xxtools — edit freely

require_relative '../base'
require_relative 'entities'
require_relative 'map'

module Engine
  module Game
    module GForge05
      class Game < Engine::Game::Base
        include Entities
        include Map

        # ── Trains ───────────────────────────────────────────────────────────
        TRAINS = [
          {
            name: '2',
            distance: 2,
            price: 80,
            num: 6,
            rusts_on: '4',
          },
          {
            name: '3',
            distance: 3,
            price: 180,
            num: 5,
            rusts_on: '6',
          },
          {
            name: '4',
            distance: 4,
            price: 300,
            num: 4,
            rusts_on: 'D',
          },
          {
            name: '5',
            distance: 5,
            price: 450,
            num: 3,
            events: [{ 'type' => 'close_companies' }],
          },
          { name: '6', distance: 6, price: 630, num: 2 },
          { name: 'D', distance: 999, price: 1100, num: 99 }
        ].freeze

        # ── Phases ───────────────────────────────────────────────────────────
        PHASES = [
          {
            name: '2',
            train_limit: 4,
            tiles: [:yellow],
            operating_rounds: 1,
          },
          {
            name: '3',
            on: '3',
            train_limit: 4,
            tiles: %i[yellow green],
            operating_rounds: 2,
            status: %w[can_buy_companies],
          },
          {
            name: '4',
            on: '4',
            train_limit: 3,
            tiles: %i[yellow green],
            operating_rounds: 2,
            status: %w[can_buy_companies],
          },
          {
            name: '5',
            on: '5',
            train_limit: 2,
            tiles: %i[yellow green brown],
            operating_rounds: 3,
          },
          {
            name: '6',
            on: '6',
            train_limit: 2,
            tiles: %i[yellow green brown],
            operating_rounds: 3,
          },
          {
            name: 'D',
            on: 'D',
            train_limit: 2,
            tiles: %i[yellow green brown],
            operating_rounds: 3,
          }
        ].freeze

        # ── Bank & Players ────────────────────────────────────────────────────
        PLAYERS_RANGE = [2, 6]
        BANK_CASH = 7_000
        CURRENCY_FORMAT_STR = '¥%s'
        STARTING_CASH = { 2 => 420, 3 => 420, 4 => 420, 5 => 390, 6 => 390 }.freeze
        CERT_LIMIT = { 2 => 25, 3 => 19, 4 => 14, 5 => 12, 6 => 11 }.freeze

        # ── Corporation Rules ─────────────────────────────────────────────────
        CAPITALIZATION = :full
        HOME_TOKEN_TIMING = :operating_round
        MARKET_SHARE_LIMIT = 50
        TRACK_RESTRICTION = :semi_restrictive
        BANKRUPTCY_ALLOWED = true
        BANKRUPTCY_ENDS_GAME_AFTER = :one

        # ── Stock Round ───────────────────────────────────────────────────────
        SELL_BUY_ORDER = :sell_buy_or_buy_sell
        SELL_MOVEMENT = :down_share
        POOL_SHARE_DROP = :none
        MUST_SELL_IN_BLOCKS = true
        SELL_AFTER = :first

        MARKET = [
                  [100,110,120,130,140,150,160,170,180,190,200]
                ].freeze

        # ── Operating Round ───────────────────────────────────────────────────
        MUST_BUY_TRAIN = :route
        ALLOW_REMOVING_TOWNS = false
        EBUY_FROM_OTHERS = :never
        EBUY_DEPOT_TRAIN_MUST_BE_CHEAPEST = true
        MUST_EMERGENCY_ISSUE_BEFORE_EBUY = false
        EBUY_OWNER_MUST_HELP = false
        EBUY_CAN_SELL_SHARES = true
        EBUY_PRES_SWAP = false
        EBUY_CAN_TAKE_PLAYER_LOAN = false

        TILE_LAYS = [{ lay: true, upgrade: true }].freeze

        # ── Game Flow ─────────────────────────────────────────────────────────
        # Initial round: Waterfall auction — configure auction in Companies panel

        # ── Game End ──────────────────────────────────────────────────────────
        # GAME_END_CHECK not configured

        # ── Special Constants ─────────────────────────────────────────────────
        # (nothing to configure)

        # ── Round Methods ─────────────────────────────────────────────────────
        # (nothing to configure)

        # ── Methods ───────────────────────────────────────────────────────────
        # (nothing to configure)

      end
    end
  end
end
