# frozen_string_literal: true
# Generated by 18xxtools — edit freely

module Engine
  module Game
    module GForge01
      module Entities
        # ── Private Companies ─────────────────────────────────────────────────
        COMPANIES = [
          {
            name: 'Takamatsu E-Railroad',
            value: 20,
            revenue: 5,
            desc: 'Blocks Takamatsu (K4) while owned by a player.',
            sym: 'TR',
            abilities: [
              { type: 'blocks_hexes', owner_type: 'player', hexes: %w[K4] },
            ],
          },
          {
            name: 'Mitsubishi Ferry',
            value: 30,
            revenue: 5,
            desc: 'Player owner may place the port tile on a coastal town (B11, G10, I12, or J9) without a tile on it already, outside of the operating rounds of a corporation controlled by another player. The player need not control a corporation or have connectivity to the placed tile from one of their corporations. This does not close the company.',
            sym: 'MF',
            abilities: [
              { type: 'tile_lay', owner_type: 'player', when: %w[stock_round owning_player_track or_between_turns], hexes: %w[B11 G10 I12 J9], count: 1, tiles: %w[437] },
            ],
          },
          {
            name: 'Ehime Railway',
            value: 40,
            revenue: 10,
            desc: 'When this company is sold to a corporation, the selling player may immediately place a green tile on Ohzu (C4), in addition to any tile which it may lay during the same operating round. This does not close the company. Blocks C4 while owned by a player.',
            sym: 'ER',
            abilities: [
              { type: 'blocks_hexes', owner_type: 'player', hexes: %w[C4] },
              { type: 'tile_lay', owner_type: 'corporation', when: 'sold', hexes: %w[C4], count: 1, tiles: %w[12 13 14 15 205 206] },
            ],
          },
          {
            name: 'Sumitomo Mines Railway',
            value: 50,
            revenue: 15,
            desc: 'Owning corporation may ignore building cost for mountain hexes which do not also contain rivers. This does not close the company.',
            sym: 'SMR',
            abilities: [
              { type: 'tile_discount', owner_type: 'corporation', discount: 80, terrain: 'mountain' },
            ],
          },
          {
            name: 'Dougo Railway',
            value: 60,
            revenue: 15,
            desc: 'Owning player may exchange this private company for a 10% share of Iyo Railway from the initial offering.',
            sym: 'DR',
            abilities: [
              { type: 'exchange', owner_type: 'player', when: 'any', corporations: %w[IR], from: 'ipo' },
            ],
          },
          {
            name: 'Reserve-Share Concession (JC)',
            value: 80,
            revenue: 10,
            desc: 'No special abilities.',
            sym: 'SIR',
            abilities: [
              { type: 'exchange', owner_type: 'player', when: 'phase_3', corporations: %w[JC], from: %w[reserved] },
            ],
          },
          {
            name: 'Uno-Takamatsu Ferry',
            value: 150,
            revenue: 30,
            desc: 'Does not close while owned by a player. If owned by a player when the first 5-train is purchased it may no longer be sold to a public company and the revenue is increased to 50.',
            sym: 'UTF',
            abilities: [
              { type: 'close', owner_type: 'player', on_phase: 'never' },
              { type: 'revenue_change', owner_type: 'player', revenue: 50, on_phase: '5' },
            ],
          },
        ].freeze

        # ── Corporations ──────────────────────────────────────────────────────
        CORPORATIONS = [
          {
            sym: '',
            name: 'Awa Railroad',
            logo: '1889/AR',
            color: '#37383a',
            text_color: '#000000',
            tokens: [0, 40],
            coordinates: 'K8',
            float_percent: 50,
          },
          {
            sym: '',
            name: 'Iyo Railway',
            logo: '1889/IR',
            color: '#f48221',
            text_color: '#000000',
            tokens: [0, 40],
            coordinates: 'E2',
            float_percent: 50,
          },
          {
            sym: '',
            name: 'Sanuki Railway',
            logo: '1889/SR',
            color: '#76a042',
            text_color: '#000000',
            tokens: [0, 40],
            coordinates: 'I2',
            float_percent: 50,
          },
          {
            sym: '',
            name: 'Takamatsu & Kotohira Electric Railway',
            logo: '1889/KO',
            color: '#d81e3e',
            text_color: '#000000',
            tokens: [0, 40],
            coordinates: 'K4',
            float_percent: 50,
          },
          {
            sym: '',
            name: 'Tosa Electric Railway',
            logo: '1889/TR',
            color: '#00a993',
            text_color: '#000000',
            tokens: [0, 40, 40],
            coordinates: 'F9',
            float_percent: 50,
          },
          {
            sym: '',
            name: 'Tosa Kuroshio Railway',
            logo: '1889/KU',
            color: '#0189d1',
            text_color: '#000000',
            tokens: [0],
            coordinates: 'C10',
            float_percent: 50,
          },
          {
            sym: '',
            name: 'Uwajima Railway',
            logo: '1889/UR',
            color: '#6f533e',
            text_color: '#000000',
            tokens: [0, 40, 40],
            coordinates: 'B7',
            float_percent: 50,
          },
          {
            sym: 'JC',
            name: 'JC Railway',
            color: '#990099',
            tokens: [0, 0, 0],
            coordinates: 'E5',
          },
        ].freeze

        # ── Minors ────────────────────────────────────────────────────────────
        # (nothing to configure)

      end
    end
  end
end
