# frozen_string_literal: true
# Generated by 18xxtools — edit freely

module Engine
  module Game
    module GGGame
      module Entities
        # ── Private Companies ─────────────────────────────────────────────────
        COMPANIES = [
          {
            name: 'Takamatsu E-Railroad',
            value: 20,
            revenue: 5,
            desc: 'Blocks Takamatsu (K4) while owned by a player.',
            sym: 'TR',
            abilities: [
              { type: 'blocks_hexes', owner_type: 'player', hexes: %w[K4] },
            ],
          },
          {
            name: 'Mitsubishi Ferry (+Extra Tile)',
            value: 30,
            revenue: 5,
            desc: 'Player owner may place the port tile on a coastal town (B11, G10, I12, or J9) without a tile on it already, outside of the operating rounds of a corporation controlled by another player. The player need not control a corporation or have connectivity to the placed tile from one of their corporations. This does not close the company.',
            sym: 'MF',
            abilities: [
              { type: 'tile_lay', owner_type: 'corporation', count: 1, closed_when_used_up: true, free: false, reachable: true },
            ],
          },
          {
            name: 'Ehime Railway',
            value: 40,
            revenue: 10,
            desc: 'When this company is sold to a corporation, the selling player may immediately place a green tile on Ohzu (C4), in addition to any tile which it may lay during the same operating round. This does not close the company. Blocks C4 while owned by a player.',
            sym: 'ER',
            abilities: [
              { type: 'blocks_hexes', owner_type: 'player', hexes: %w[C4] },
              { type: 'tile_lay', owner_type: 'corporation', when: 'sold', hexes: %w[C4], count: 1, tiles: %w[12 13 14 15 205 206] },
            ],
          },
          {
            name: 'Sumitomo Mines Railway',
            value: 50,
            revenue: 15,
            desc: 'Owning corporation may ignore building cost for mountain hexes which do not also contain rivers. This does not close the company.',
            sym: 'SMR',
            abilities: [
              { type: 'tile_discount', owner_type: 'corporation', discount: 80, terrain: 'mountain' },
            ],
          },
          {
            name: 'Dougo Railway',
            value: 60,
            revenue: 15,
            desc: 'Owning player may exchange this private company for a 10% share of Iyo Railway from the initial offering.',
            sym: 'DR',
            abilities: [
              { type: 'exchange', owner_type: 'player', when: 'any', corporations: %w[IR], from: 'ipo' },
            ],
          },
          {
            name: 'South Iyo Railway',
            value: 80,
            revenue: 20,
            desc: 'No special abilities.',
            sym: 'SIR',
          },
          {
            name: 'Uno-Takamatsu Ferry',
            value: 150,
            revenue: 30,
            desc: 'Does not close while owned by a player. If owned by a player when the first 5-train is purchased it may no longer be sold to a public company and the revenue is increased to 50.',
            sym: 'UTF',
            abilities: [
              { type: 'close', owner_type: 'player', on_phase: 'never' },
              { type: 'revenue_change', owner_type: 'player', on_phase: '5' },
            ],
          },
        ].freeze

        # ── Corporations ──────────────────────────────────────────────────────
        # (nothing to configure)

        # ── Minors ────────────────────────────────────────────────────────────
        # (nothing to configure)

      end
    end
  end
end
