# frozen_string_literal: true
# Generated by 18xxtools — edit freely

module Engine
  module Game
    module GGGame
      module Entities
        # ── Private Companies ─────────────────────────────────────────────────
        COMPANIES = [
          {
            name: 'Water Engineer',
            value: 80,
            revenue: 10,
            desc: 'One free water upgrade, or $10 discount on all water upgrades.',
            sym: '',
            abilities: [
              { type: 'tile_discount', owner_type: 'corporation', discount: 10, terrain: 'water' },
            ],
          },
        ].freeze

        # ── Corporations ──────────────────────────────────────────────────────
        # (nothing to configure)

        # ── Minors ────────────────────────────────────────────────────────────
        # (nothing to configure)

      end
    end
  end
end
