# frozen_string_literal: true
# Generated by 18xxtools — edit freely

require_relative '../base'
require_relative 'entities'
require_relative 'map'

module Engine
  module Game
    module GForge14
      class Game < Engine::Game::Base
        include Entities
        include Map

        # ── Trains ───────────────────────────────────────────────────────────
        TRAINS = [
          { name: '2', distance: 2, price: 80, rusts_on: '6' },
          {
            name: '4',
            distance: 4,
            price: 180,
            variants: [
              { name: '3/5', distance: 1, price: 160 }
            ],
          },
          {
            name: '5',
            distance: 5,
            price: 500,
            events: [{ 'type' => 'close_companies' }],
            variants: [
              { name: '4/6', distance: 1, price: 450 }
            ],
          },
          {
            name: '6',
            distance: 6,
            price: 800,
            events: [{ 'type' => 'remove_bonuses' }, { 'type' => 'remove_reservations' }],
            variants: [
              { name: '7/8', distance: 1, price: 900 }
            ],
          }
        ].freeze

        # ── Phases ───────────────────────────────────────────────────────────
        PHASES = [
          {
            name: 'I',
            train_limit: 4,
            tiles: [:yellow],
            operating_rounds: 2,
            status: %w[can_buy_companies],
          },
          {
            name: 'II',
            on: '4',
            train_limit: 4,
            tiles: %i[yellow green],
            operating_rounds: 2,
            status: %w[can_buy_companies],
          },
          {
            name: 'III',
            on: '5',
            train_limit: 3,
            tiles: %i[yellow green brown],
            operating_rounds: 2,
          },
          {
            name: 'IV',
            on: '6',
            train_limit: 2,
            tiles: %i[yellow green brown grey],
            operating_rounds: 2,
          }
        ].freeze

        # ── Bank & Players ────────────────────────────────────────────────────
        PLAYERS_RANGE = [2, 5]
        BANK_CASH = 12_000
        STARTING_CASH = { 2 => 600, 3 => 400, 4 => 400, 5 => 400 }.freeze
        CERT_LIMIT = { 2 => 0, 3 => 0, 4 => 6, 5 => 8 }.freeze

        # ── Corporation Rules ─────────────────────────────────────────────────
        CAPITALIZATION = :full
        HOME_TOKEN_TIMING = :float
        MARKET_SHARE_LIMIT = 50
        TRACK_RESTRICTION = :semi_restrictive
        BANKRUPTCY_ALLOWED = true
        BANKRUPTCY_ENDS_GAME_AFTER = :all_but_one

        # ── Stock Round ───────────────────────────────────────────────────────
        SELL_BUY_ORDER = :sell_buy
        SELL_MOVEMENT = :left_block_pres
        POOL_SHARE_DROP = :down_block
        MUST_SELL_IN_BLOCKS = true
        SELL_AFTER = :p_any_operate

        MARKET = [
                  [100,110,120,130,140,150,160,170,180,190,200]
                ].freeze

        # ── Operating Round ───────────────────────────────────────────────────
        MUST_BUY_TRAIN = :always
        ALLOW_REMOVING_TOWNS = false
        EBUY_FROM_OTHERS = :never
        EBUY_DEPOT_TRAIN_MUST_BE_CHEAPEST = false
        MUST_EMERGENCY_ISSUE_BEFORE_EBUY = true
        EBUY_OWNER_MUST_HELP = false
        EBUY_CAN_SELL_SHARES = true
        EBUY_PRES_SWAP = true
        EBUY_CAN_TAKE_PLAYER_LOAN = false

        TILE_LAYS = [{ lay: true, upgrade: true }, { lay: true, upgrade: true }].freeze

        # ── Game Flow ─────────────────────────────────────────────────────────
        # Initial round: Waterfall auction — configure auction in Companies panel

        # ── Game End ──────────────────────────────────────────────────────────
        GAME_END_CHECK = { bank: :full_or, bankrupt: :immediate, all_closed: :immediate, final_train: :one_more_full_or_set }.freeze

        # ── Special Constants ─────────────────────────────────────────────────
        # (nothing to configure)

        # ── Round Methods ─────────────────────────────────────────────────────
        # (nothing to configure)

        # ── Methods ───────────────────────────────────────────────────────────
        # Private company accessors — reference by name in custom step code.

        def steamboat
          @steamboat ||= company_by_id('SC')
        end

        def boomtown
          @boomtown ||= company_by_id('BT')
        end

      end
    end
  end
end
