# frozen_string_literal: true
# Generated by 18xxtools — edit freely

module Engine
  module Game
    module GGGame
      module Entities
        # ── Private Companies ─────────────────────────────────────────────────
        # (nothing to configure)

        # ── Corporations ──────────────────────────────────────────────────────
        # (nothing to configure)

        # ── Minors ────────────────────────────────────────────────────────────
        # (nothing to configure)

      end
    end
  end
end
