# frozen_string_literal: true
# Generated by 18xxtools — edit freely

require_relative '../meta'

module Engine
  module Game
    module GForge28
      module Meta
        include Game::Meta

        DEV_STAGE = :alpha

        GAME_TITLE = 'Forge28'
      end
    end
  end
end
