# frozen_string_literal: true
# Generated by 18xxtools — edit freely

module Engine
  module Game
    module GForge21
      module Entities
        # ── Private Companies ─────────────────────────────────────────────────
        COMPANIES = [
          {
            name: 'Michigan Southern (Minor)',
            value: 60,
            revenue: 0,
            desc: 'Starts with $60, a 2 train, and a token in Detroit (C15). Always operates first. Its train may run in OR1. Splits dividends equally with owner. Purchasing company receives its cash, train and token but cannot run this 2 train in the same OR in which the MS operated. ',
            sym: 'MS',
          },
          {
            name: 'Big 4 (Minor)',
            value: 40,
            revenue: 0,
            desc: 'Starts with $40, a 2 train, and a token in Indianapolis (G9). Always operates after the MS and before other corporations. Its train may run in OR1. Splits dividends equally with owner. Purchasing company receives its cash, train and token but cannot run this 2 train in the same OR in which the BIG4 operated. ',
            sym: 'BIG4',
          },
          {
            name: 'Chicago and Western Indiana',
            value: 60,
            revenue: 10,
            desc: 'Reserves a token slot in the southeast entrance to Chicago (D6) next to E7. Owning corporation may place an extra token there for free (no connection required). Reservation is removed once this company is purchased by a corporation or closed.',
            sym: 'C&WI',
            abilities: [
              { type: 'token', owner_type: 'corporation', when: 'owning_corp_or_turn', hexes: %w[D6], count: 1, price: 0 },
              { type: 'reservation', hex: '' },
            ],
          },
          {
            name: 'Mail Contract',
            value: 80,
            revenue: 0,
            desc: 'Adds a $10 bonus for each city visited by a single train of the owning corporation. Never closes once purchased by a corporation. Closes on Phase III if owned by a player',
            sym: 'MAIL',
            abilities: [
              { type: 'close', owner_type: 'corporation', on_phase: 'never' },
            ],
          },
          {
            name: 'Tunnel Blasting Company',
            value: 60,
            revenue: 20,
            desc: 'Reduces the cost of laying tiles on mountains (hexes with a brown triangle) and connecting hexes with tunnels (brown hex edges) by $20 for the owning corporation.',
            sym: 'TBC',
            abilities: [
              { type: 'tile_discount', owner_type: 'corporation', discount: 20, terrain: 'mountain' },
            ],
          },
          {
            name: 'Meat Packing Company',
            value: 60,
            revenue: 15,
            desc: 'Adds a $30 bonus to either St. Louis (I1) or Chicago (D6) for the owning corporation. Bonus must be assigned after being purchased by a corporation. Bonus persists after this company closes in Phase III but is removed in Phase IV.',
            sym: 'MPC',
            abilities: [
              { type: 'assign_hexes', owner_type: 'corporation', when: 'owning_corp_or_turn', hexes: %w[I1 D6], count: 1 },
              { type: 'assign_corporation', owner_type: 'corporation', when: 'sold', count: 1 },
            ],
          },
          {
            name: 'Steamboat Company',
            value: 40,
            revenue: 10,
            desc: 'Add a bonus to the value of one port city, either a $40 bonus to Wheeling (G19) / Holland (B8) or a $20 bonus to Chicago Conn. (C5) / Toledo (D14) / St. Louis (I1). At the beginning of each OR, this company\'s owner may reassign this bonus to a different port city and/or train company (including minors). Once purchased by a corporation, it becomes permanently assigned to that corporation. Bonus persists after this company closes in Phase III but is removed in Phase IV.',
            sym: 'SC',
            abilities: [
              { type: 'assign_hexes', owner_type: 'player', when: 'or_start', hexes: %w[B8 C5 D14 I1 G19], count_per_or: 1 },
              { type: 'assign_corporation', owner_type: 'player', when: 'or_start', count_per_or: 1 },
              { type: 'assign_hexes', owner_type: 'corporation', when: %w[track_and_token route], hexes: %w[B8 C5 D14 I1 G19], count_per_or: 1 },
              { type: 'assign_corporation', owner_type: 'corporation', when: 'sold', count: 1 },
            ],
          },
          {
            name: 'Lake Shore Line',
            value: 40,
            revenue: 15,
            desc: 'Owning corporation may make an extra free green tile upgrade of either Cleveland (E17) or Toledo (D14).',
            sym: 'LSL',
            abilities: [
              { type: 'tile_lay', owner_type: 'corporation', when: 'owning_corp_or_turn', hexes: %w[D14 E17], count: 1, tiles: %w[14 15 619 294 295 296], free: true },
            ],
          },
          {
            name: 'Michigan Central',
            value: 40,
            revenue: 15,
            desc: 'Owning corporation may lay up to two extra free yellow tiles in reserved hexes B10 and B12. If both tiles are laid, they must connect to each other. Owning corporation does not need to be connected to either hex to use this ability.',
            sym: 'MC',
            abilities: [
              { type: 'blocks_hexes', owner_type: 'player', hexes: %w[B10 B12] },
              { type: 'tile_lay', owner_type: 'corporation', when: 'owning_corp_or_turn', hexes: %w[B10 B12], count: 2, tiles: %w[7 8 9], free: true },
            ],
          },
          {
            name: 'Ohio & Indiana',
            value: 40,
            revenue: 15,
            desc: 'Owning corporation may lay up to two extra free yellow tiles in reserved hexes F14 and F16. If both tiles are laid, they must connect to each other. Owning corporation does not need to be connected to either hex to use this ability.',
            sym: 'O&I',
            abilities: [
              { type: 'blocks_hexes', owner_type: 'player', hexes: %w[F14 F16] },
              { type: 'tile_lay', owner_type: 'corporation', when: 'owning_corp_or_turn', hexes: %w[F14 F16], count: 2, tiles: %w[7 8 9], free: true },
            ],
          },
          {
            name: 'Boomtown',
            value: 40,
            revenue: 10,
            desc: 'Adds a $20 bonus to Cincinnati (H12) for the owning corporation. Bonus must be assigned after being purchased by a corporation. Bonus persists after this company closes in Phase III but is removed in Phase IV.',
            sym: 'BT',
            abilities: [
              { type: 'assign_hexes', owner_type: 'corporation', when: 'owning_corp_or_turn', hexes: %w[H12], count: 1 },
              { type: 'assign_corporation', owner_type: 'corporation', when: 'sold', count: 1 },
            ],
          },
          {
            name: 'Little Miami',
            value: 40,
            revenue: 15,
            desc: 'If no track connects Cincinnati (H12) to Dayton (G13), the owning corporation may lay and/or upgrade an extra free tile in each hex to connect them. Owning corporation does not need to be connected to either hex to use this ability.',
            sym: 'LM',
            abilities: [
              { type: 'tile_lay', owner_type: 'corporation', when: 'owning_corp_or_turn', hexes: %w[H12 G13], count: 2, discount: 20, tiles: %w[5 6 57 14 15 619 291 292 293 294 295 296], reachable: false },
            ],
          },
          {
            name: 'L-Train Concession',
            value: 100,
            revenue: 0,
            desc: 'Grants the owning corporation a permanent L train.',
            sym: '',
            abilities: [
              { type: 'generic', subtype: 'generic' },
            ],
          },
        ].freeze

        # ── Corporations ──────────────────────────────────────────────────────
        # (nothing to configure)

        # ── Minors ────────────────────────────────────────────────────────────
        # (nothing to configure)

      end
    end
  end
end
