# frozen_string_literal: true
# Generated by 18xxtools — edit freely

require_relative '../meta'

module Engine
  module Game
    module GForge23
      module Meta
        include Game::Meta

        DEV_STAGE = :alpha

        GAME_TITLE = 'Forge23'
      end
    end
  end
end
